src/github.py
src/release.py

@EPashkin: Like this you won't have to get all merged PRs at every release (and thanks so much for doing it!). ;)

Get merged PRs to build blog post

---

src/my_toml.py
src/release.py
src/utils.py

cc @EPashkin
Next release, the order of the `Cargo.toml` lines will remain the same.

Keep line order in Cargo files

---

src/release.py
src/utils.py

Fixes #15.
As usual, will be tested when doing next release.
cc @sdroege

Generate tags when releasing

---

src/release.py

Add gir merged PRs in blog post as well

---

src/release.py

Minor fixes

---

src/my_toml.py
src/release.py

Fix toml parsing

---

src/release.py

Fix search-index.js generation

---

src/release.py

Add message before publishing a crate

---

src/release.py

change cced people on prs

---

src/release.py

Fix invalid blog post generation for gir

---

src/release.py

Create PR for examples repository as well

---

src/release.py

Open examples PR after crates being published

---

src/consts.py

Add gtk-test repository to the release

---

src/release.py

Fixes #49.
Still needs to be tested though but I think I'm close to the end...

Create multiple tags if more than one crate in a repository

---

src/release.py

Generate source files as well

---

src/release.py

Its copied to right location on next copy
See https://github.com/gtk-rs/docs/pull/24#issuecomment-475978054
@GuillaumeGomez can you create PR to docs with this?

Remove copy sources to crate auto folder

---

src/release.py

escape "[" and "]" characters in PRs title

---

src/release.py

Don't checkout crate branch for lgpl-docs repository before publishing

---

src/release.py

Fix string indent

---

src/release.py

Add messages when generating documentation to keep track of what's going on

---

src/release.py

Sort pull requests in reverse number order

---

src/release.py

Sort contributors alphabetically with case insensitive

---

.pylintrc
.travis.yml
src/__init__.py
src/consts.py
src/github.py
src/globals.py
src/release.py
src/utils.py

Lint and checks

---

src/args.py
src/release.py

Move argument parsing into its file and class

---

.gitignore
src/args.py
src/release.py

More options

---

.pylintrc
minifier/Cargo.lock
setup.py
src/__init__.py
src/args.py
src/release.py
src/utils.py

Check nightly

---

src/consts.py
src/release.py

Add gdkx11 to the crate list

---

setup.py

Hi all
This is a followup to https://github.com/gtk-rs/gtk/pull/1054
Cheers,
Stefan

Use https for all links

---

src/args.py
src/consts.py
src/my_toml.py
src/release.py
src/utils.py

Update script to new release system

---

src/release.py
src/utils.py

Switch to the previous release branch to get the oldest_date to be used to retrieve all gir PRs
